// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSeLQCKR1PJi6DLAYhu_MqRlsvONKeTKQ',
    appId: '1:359337219224:web:0417314f99e7194976eced',
    messagingSenderId: '359337219224',
    projectId: 'app-asher-lungscan-ai',
    authDomain: 'app-asher-lungscan-ai.firebaseapp.com',
    storageBucket: 'app-asher-lungscan-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbY-nqAqmb4r74bsEeUz2qvHFwoMaddx0',
    appId: '1:359337219224:android:e505310c1a44cb3e76eced',
    messagingSenderId: '359337219224',
    projectId: 'app-asher-lungscan-ai',
    storageBucket: 'app-asher-lungscan-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARXRKnn6pKlTfkRyTQw0ZqUbAmDTFi4cE',
    appId: '1:359337219224:ios:d9168a9d70c1f3b776eced',
    messagingSenderId: '359337219224',
    projectId: 'app-asher-lungscan-ai',
    storageBucket: 'app-asher-lungscan-ai.firebasestorage.app',
    iosClientId: '359337219224-itp2qmil9be2rc1a6spat2on5a17ai5e.apps.googleusercontent.com',
    iosBundleId: 'app.asher.lungscanAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARXRKnn6pKlTfkRyTQw0ZqUbAmDTFi4cE',
    appId: '1:359337219224:ios:d9168a9d70c1f3b776eced',
    messagingSenderId: '359337219224',
    projectId: 'app-asher-lungscan-ai',
    storageBucket: 'app-asher-lungscan-ai.firebasestorage.app',
    iosClientId: '359337219224-itp2qmil9be2rc1a6spat2on5a17ai5e.apps.googleusercontent.com',
    iosBundleId: 'app.asher.lungscanAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSeLQCKR1PJi6DLAYhu_MqRlsvONKeTKQ',
    appId: '1:359337219224:web:e7f5a9d8716950dd76eced',
    messagingSenderId: '359337219224',
    projectId: 'app-asher-lungscan-ai',
    authDomain: 'app-asher-lungscan-ai.firebaseapp.com',
    storageBucket: 'app-asher-lungscan-ai.firebasestorage.app',
  );

}